### ISSUE TITLE
info.json について

### ISSUE THREAD

**Issue by Rookie-999** [J-Tech-Creations/Avocado55#1]
make したのですが、info.jsonのキー割り当てが5Keyしか無いとエラーが出ます。
info.jsonの中でキーの割当方法が知りたいです。お手数をお掛けしますが、ご確認をお願いします。
![キャプチャ](https://user-images.githubusercontent.com/124848369/217692555-314d4df9-d053-41f9-95ce-4ac3e1d060aa.PNG)

**Comment by Rookie-999** [comment]
キー割り当てはできましたが、今度はpointing_device_drivers.cでエラーが出て内容分からずお手上げです。
![Uploading キャプチャ.PNG…]()

**Comment by tomohisa** [comment]
```
git clone https://github.com/tomohisa/qmk_firmware.git
```
こちらのソースをロードしておられると思います。
qmk --version 
の出力はどうなりますでしょうか？
環境は、mac, windowsいずれでしょうか？

**Comment by Rookie-999** [comment]
お世話になります。
お教え頂いたもので出力されたのは1.0.0でした。
環境はWindowsになります。

**Comment by Rookie-999** [comment]
> ```
> git clone https://github.com/tomohisa/qmk_firmware.git
> ```
> 
> こちらのソースをロードしておられると思います。 qmk --version の出力はどうなります か？

お世話になります。
ソースは公開されているものを使用させてもらいました。
qmkのversionは1.0.0でした。環境はWindowsになります。

**Comment by tomohisa** [comment]
こちらですが、私の作成した時と最新のQMKでトラッキングデバイス対応が大幅に違うことが原因のようです。QMK_MSYS 1.3くらいがインストールできれば、ビルドできそうな気がします

**Comment by Rookie-999** [comment]
お世話になっております。MSYSを起動してpacman -Syuを入力してもVersionの更新がされません。再インストールしたほうが良いのでしょうか。また、公開されているソースの内容を少しいじってしまったのですが、本来は公開されているものをそのまま使用でよろしかったでしょうか。info.jsonでキー数が異なるとエラーが出てしまっていたので。。。

**Comment by Rookie-999** [comment]
![キャプチャ](https://user-images.githubusercontent.com/124848369/217988179-1a231650-2cdb-4fdb-afec-3c00b9837390.PNG)
お世話になっております。現在の状況はMSYSを再インストールし再度公開されているソースをロード。makeした時にエラーが出る状態です。qmkのversionは1.1.1になりました。これを1.3にする方法が見つからず難航しています。

**Comment by tomohisa** [comment]
https://github.com/qmk/qmk_distro_msys/releases/tag/1.3.0
こちらが QMK_MSYS 1.3となりますとき、QMKのバージョンは1.1より古くなるかもです

https://github.com/tomohisa/qmk_firmware/tree/handwire_tomohisa
上記のブランチが、開発当時のもので、新しいQMKとマージしていないものです。

こちらのブランチで、古いQMKで試すとできるのかもしれません。

新しいQMKに対応するのが一番と思うのですが、すぐに対応の時間が取れそうになく、申し訳ありません。

**Comment by Rookie-999** [comment]
お世話になっております。ご確認･ご連絡有難う御座います。
お教え頂いたQMK_MSYSををインストールしてみます。
ブランチに関しては申し訳ございません。どのようにすれば良いのでしょうか?
分かっておらず申し訳ございません。教えて頂けますと幸いです。

**Comment by tomohisa** [comment]
https://docs.github.com/ja/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/managing-branches#switching-between-branches
ご参考にされてください

**Comment by Rookie-999** [comment]
お世話になっております。何度も申し訳ございません。
開発当時のブランチをクローンに成功しましたが、QMKを教えていただきましたリンクで、再インストールしQMK SETUPを実行してVersionを確認したら1.1.1となっていました。試しにmakeしてみた結果、先般連絡致しましたエラーが出てきます。
もうどのようにすればよいか全く分からず、大変申し訳ございませんが、助けて頂けますと幸いです。

**Comment by tomohisa** [comment]
ChatGPTに古いQMKを使う方法について聞いて見ました。
なんとか使えて欲しいと思っているのですが、基本的なソフトの使用方法までを教えることはなかなか難しいです。
ーーー
https://github.com/qmk/qmk_toolbox
こちらで使えるファームウェアファイルを私の方から送るなどは可能性としてできるかもしれません。
ーーー

To use an older version of the QMK Firmware in Windows, you can follow these steps:

Download the desired version of the QMK Firmware from the QMK Github repository (https://github.com/qmk/qmk_firmware).
Install Git for Windows if you don't have it already. You can download it from https://git-scm.com/download/win.
Open a Git Bash terminal (you can do this by searching for "Git Bash" in the Start menu or by right-clicking on the Windows File Explorer and selecting "Git Bash Here").
Navigate to the directory where you want to install the QMK Firmware by using the cd command in Git Bash. For example, cd ~/qmk_firmware.
Clone the desired version of the QMK Firmware by using the following command:
bash
Copy code
git clone https://github.com/qmk/qmk_firmware.git -b [branch_name] --depth 1
Replace [branch_name] with the name of the branch that corresponds to the desired version of the firmware.

Once the clone is complete, navigate into the cloned repository by using the following command:
bash
Copy code
cd qmk_firmware
Use the following command to install the dependencies required to build the firmware:
bash
Copy code
util/install_dependencies.sh
You should now be able to build your firmware as described in the QMK documentation (https://docs.qmk.fm/#/getting_started_build_tools).
I hope this helps! Let me know if you have any additional questions.

**Comment by Rookie-999** [comment]
お世話になっております。
ご連絡有難う御座います。
お手数をお掛けしますが、送って頂いても宜しいでしょうか。
そうしますと、自分でキーマップの変更は出来ないですよね？

**Comment by tomohisa** [comment]
https://www.dropbox.com/s/xqpeza2789720r6/firmwares_avocado.zip?dl=0
こちらでお試し下さい。ご自分でのキーマップの変更はご自分でビルドした時になります。どこかで新しいQMKに対応できるかやって見たいと思います。。

**Comment by Rookie-999** [comment]
有難う御座います。
頂いた物で書き込みが無事に出来ました。
私も教えて頂いたやり方で再度ビルド出来ないかを試そうかと思います。
新しいQMKに対応出来るかのトライをして頂けるとのことで、もし、完成しましたら使わせて頂きたいです。

**Comment by Rookie-999** [comment]
お世話になっております。
QMK1.3をインストールでき、今回教えて頂きましたソースをクローンしたものでビルドを行った結果、エラーが出ました。
このエラーはクローンが正常にできていないためでしょうか。
![image](https://user-images.githubusercontent.com/124848369/218419675-b790abb6-c946-48aa-b485-531545902d96.png)

**Comment by Rookie-999** [comment]
度々申し訳ございません。
厚かましいお願いかとは思いますが、希望するキーマップでビルドしていただくことは可能でしょうか?

**Comment by tomohisa** [comment]
https://github.com/tomohisa/qmk_firmware
こちらをのmasterを最新版に対応してみました。試してみることができるかもしれません

**Comment by Rookie-999** [comment]
ご連絡有難う御座います。
頂いた物で動きました。
